// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/2/2025, 4:30:28 p. m.
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/jmartinezi/source/repos/lucky-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jmartinezi/source/repos/lucky-front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jmartinezi/source/repos/lucky-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jmartinezi/source/repos/lucky-front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jmartinezi/source/repos/lucky-front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jmartinezi/source/repos/lucky-front/plugins/**/*.{js,ts,mjs}","C:/Users/jmartinezi/source/repos/lucky-front/composables/**/*.{js,ts,mjs}","C:/Users/jmartinezi/source/repos/lucky-front/utils/**/*.{js,ts,mjs}","C:/Users/jmartinezi/source/repos/lucky-front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jmartinezi/source/repos/lucky-front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jmartinezi/source/repos/lucky-front/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;